### ISSUE TITLE
warning in MC calculation

### ISSUE THREAD

**Issue by flaxter** [flaxter/BO-BART#1]
Here's the code from Normal.R:

```for (i in 1:300){
  CandidateSet<-rmvnorm(1*i,mean=rep(0,dim));
  integration<-mean(f1(CandidateSet))
  meanValue2<-append(meanValue2,integration);
  sd2<-append(sd2,sqrt(var(meanValue2)))
}
```

And here's what R says:

```Warning messages:
1: In y[i] <- cos(x[i]) + x :
  number of items to replace is not a multiple of replacement length
```

@OoAugust ?

**Comment by flaxter** [comment]
Similarly:

```
trainY<-f1(trainX)
```

Throws this warning:
```
Warning messages:
1: In y[i] <- cos(x[i]) + x :
  number of items to replace is not a multiple of replacement length
2: In y[i] <- cos(x[i]) + x :
  number of items to replace is not a multiple of replacement length
3: In y[i] <- cos(x[i]) + x :
  number of items to replace is not a multiple of replacement length
```

**Comment by RuyaKang** [comment]
> Here's the code from Normal.R:
> 
> ```
>   CandidateSet<-rmvnorm(1*i,mean=rep(0,dim));
>   integration<-mean(f1(CandidateSet))
>   meanValue2<-append(meanValue2,integration);
>   sd2<-append(sd2,sqrt(var(meanValue2)))
> }
> ```
> And here's what R says:
> 
> ```
> 1: In y[i] <- cos(x[i]) + x :
>   number of items to replace is not a multiple of replacement length
> ```
> @OoAugust ?

I have already changed the original test function to a continuous Genz function and changed f1. There is no error reported but it seems that we could not integrate f(x)p(x) analytically. I will update the code once I finish debugging.
