### ISSUE TITLE
Error in MI and GP calculations 

### ISSUE THREAD

**Issue by harrisonzhu508** [flaxter/BO-BART#13]
![issue](https://user-images.githubusercontent.com/30379161/50924968-e7c29280-1448-11e9-9c41-137c48cb1c71.PNG)
See above that the *"real"* value computed is not the same as results obtained by **GP** and **MI**. There are therefore 2 possibilities:

1. We messed up the genz function and carried it on into GP and MI

2. The integral computed by `adaptIntegrate(genz,lowerLimit = rep(0,dim), upperLimit = rep(1,dim))` is correct. 

This was for genz 2 with 5 dimension and 1000 iterations, run on the maths nextgen cluster, and took 16:08:56 hours.

Any thoughts? @OoAugust @RuyaKang @XingLLiu

**Comment by XingLLiu** [comment]
I checked the copeakIntegral.R function and it turns out that there's a bug in it. I created a pull request for the corrected version together with some other changes to integrationMain.R.

**Comment by harrisonzhu508** [comment]
Ok nice 1,2,4,5,6 seem to be working now. Just need to see what the results are like
