### ISSUE TITLE
Mixture genz?

### ISSUE THREAD

**Issue by harrisonzhu508** [flaxter/BO-BART#35]
Approximation wasn't great?

- Try it again
- Categorical values must be included as dummies
- Assumed that the Genz functions are uncorrelated. Could make them correlated by using different a and u values for each Genz.

**Comment by XingLLiu** [comment]
- Categorical values must be included as dummies
-

**Comment by flaxter** [comment]
@OoAugust any updates?

**Comment by harrisonzhu508** [comment]
Let's try and get this before the end the week. Once the code is pushed i can run the whole thing on the HPC cluster

**Comment by RuyaKang** [comment]
> Let's try and get this before the end the week. Once the code is pushed i can run the whole thing on the HPC cluster

Results for 1D is in my branch. Haven’t been able to get analytical result for 20D. May need help.

**Comment by harrisonzhu508** [comment]
Taking a look tonight

**Comment by harrisonzhu508** [comment]
I changed it to the below as it makes more sense to have corner peak in [0,0.5) instead. There was also a typo in the old code, where we actually applied cont to both domains
![Rplot](https://user-images.githubusercontent.com/30379161/70662830-ec965480-1c5e-11ea-9424-b7b40759b40a.png)

```mix <- function(xx){
  
  ##########################################################################
  #
  # MIXTURE GENZ FUNCTION
  #
  # yi = copeak(xi) for xi <= 0.5, cont(xi) otherwise
  # y = sum(yi)
  #
  ##########################################################################
  
  
  
  if (is.matrix(xx) == FALSE) { 
    xx <- matrix(xx, nrow = 1)  
  }
  
  dim <- ncol(xx)
  
  yval <- function(x, dim){
    
    indices_0 <- which(x <= 0.5)
    indices_1 <- which(x > 0.5)
    
    y0 <- sum(apply(as.matrix(x[indices_0]), 1, copeak))
    y1 <- sum(apply(as.matrix(x[indices_1]), 1, cont))
    
    y <- y0+y1
    
    return(y)
  }
  # Compute Genz function values
  y <- apply(xx, 1, yval)
  
  return(as.matrix(y))
}```

**Comment by RuyaKang** [comment]
> I changed it to the below as it makes more sense to have corner peak in [0,0.5) instead. There was also a typo in the old code, where we actually applied cont to both domains
> ![Rplot](https://user-images.githubusercontent.com/30379161/70662830-ec965480-1c5e-11ea-9424-b7b40759b40a.png)
> 
> ```
>   
>   ##########################################################################
>   #
>   # MIXTURE GENZ FUNCTION
>   #
>   # yi = copeak(xi) for xi <= 0.5, cont(xi) otherwise
>   # y = sum(yi)
>   #
>   ##########################################################################
>   
>   
>   
>   if (is.matrix(xx) == FALSE) { 
>     xx <- matrix(xx, nrow = 1)  
>   }
>   
>   dim <- ncol(xx)
>   
>   yval <- function(x, dim){
>     
>     indices_0 <- which(x <= 0.5)
>     indices_1 <- which(x > 0.5)
>     
>     y0 <- sum(apply(as.matrix(x[indices_0]), 1, copeak))
>     y1 <- sum(apply(as.matrix(x[indices_1]), 1, cont))
>     
>     y <- y0+y1
>     
>     return(y)
>   }
>   # Compute Genz function values
>   y <- apply(xx, 1, yval)
>   
>   return(as.matrix(y))
> }```
> ```

Have corrected it. Just pushed the new results and the results for 2D.

**Comment by RuyaKang** [comment]
Used this setting

y0 <- sum(apply(as.matrix(x[indices_0]), 1, cont))
y1 <- sum(apply(as.matrix(x[indices_1]), 1, copeak))

Will get a result for copeak on [0, 0.5) tonight.

**Comment by harrisonzhu508** [comment]
Code merged

**Comment by harrisonzhu508** [comment]
```
# analytical integrals for mixture genz
if (whichGenz == 8 & dim ==1){ real <- 0.006669431}
if (whichGenz == 8 & dim ==2){ real <- 0.006669431*2}
if (whichGenz == 8 & dim ==3){ real <- 0.006669431*3}
```

There was a bug up there, which is now fixed (whichGenz ==7, it was)

**Comment by harrisonzhu508** [comment]
See email. I have attached some BART posterior plots, but not the BART-BQ posteriors yet.

**Comment by harrisonzhu508** [comment]
Current working on 1 mixed genz
