### ISSUE TITLE
Tune the GP hyperparameters

### ISSUE THREAD

**Issue by flaxter** [flaxter/BO-BART#38]
@harrisonzhu508  has python code for this.

**Comment by harrisonzhu508** [comment]
Instead of python, we will do it in R

**Comment by harrisonzhu508** [comment]
The GPBQ.R module will have to be updated to include the tuning of RBF lengthscale and scale factors

**Comment by harrisonzhu508** [comment]
This is making headway - using `reticulate` to pass R data structures to Python, where we optimise hyperparameters using `gpytorch`. The Python code will return the optimised value.
