### ISSUE TITLE
Step function

### ISSUE THREAD

**Issue by flaxter** [flaxter/BO-BART#39]
We should do the most simple example, e.g. a function that is -1 on [0 to 0.25), 1 on [0.25, 0.5), -1 on [0.5, 0.75) and 1 on [0.75, 1) so we can (hopefully) get results that way outperform GP. We should also make plots of this, to be able to illustrate what is going on, comparing a GP with uncertainty to BART with uncertainty.

**Comment by harrisonzhu508** [comment]
@harrisonzhu508 code up function. -> integrate into main

**Comment by XingLLiu** [comment]
I ran the pipeline with f(x) = 0 for x \in [0, 0.75], 1 for x \in (0.75, 1]. The Monte Carlo result looks good but GP and BART both have an abnormal bias, which appear to persist even if I increase the number of iteration to >1000. 

To reproduce the plot, run `Rscript test_step_func.R 1 500 7`

I was suspecting that there's a bug in my code so I didn't push these test scripts into the main repo.

![results](https://user-images.githubusercontent.com/41908496/66415257-1b8c1200-e9f3-11e9-84f8-9373d75bdfae.jpg)

**Comment by harrisonzhu508** [comment]
Could we have a look at your code?

**Comment by harrisonzhu508** [comment]
I think there might be a bug in your code! @XingLLiu the integral should be 0.25 and the MC integration should be unbiased

**Comment by flaxter** [comment]
ah, the function is actually: 

```
function(xx)
{
  if (is.matrix(xx) == FALSE) { 
    xx <- matrix(xx, nrow = 1)  
  }
  
  dim <- ncol(xx)
  
  y <- matrix(NA, nrow = dim(xx)[1])
  for (i in 1:dim(xx)[1]){
      if (sum(xx[i, ] < 0.3) == dim){
          y[i, ] <- 0
      }
      else{
          y[i, ] <- 1
      }
  }

  return(y)
}
```

**Comment by flaxter** [comment]
Can someone explain this bit of the code?

```
# prepare training dataset
trainX <- randomLHS(100, dim)
source("./genz/rejection_samp.R")
trainX <- rejection_samp(N = 100, lower_lim = 0, upper_lim = 1, M = 1, f_func = genz)
trainY <- genz(trainX)
```

It ends up with a very biased set of training data, trainX is always  > 1...

**Comment by harrisonzhu508** [comment]
We were thinking of sampling more points in the peaks using rejection sampling since we didn't have enough training data at the peaks (causing poor approximations) - would this sound reasonable?

**Comment by flaxter** [comment]
Maybe! In principle a biased starting sample is fine. But ideally we wouldn't need to do this. And the fact that we have absolutely not data for trainX < 0.3 isn't good, right?

**Comment by harrisonzhu508** [comment]
that's true... I think we'll just stick to the usual uniform sampled data then!

**Comment by flaxter** [comment]
OK, there's something weird with this transformation:

```
integrals <- (integrals + 0.5) * (ymax - ymin) + ymin
```

![image](https://user-images.githubusercontent.com/59355/66848822-a75eea80-ef6d-11e9-8d28-4a2564878b9b.png)

MWE attached (stripped down version of Jerome's test_step_func.R).
[test_step_func0.R.txt](https://github.com/flaxter/BO-BART/files/3730314/test_step_func0.R.txt)

**Comment by flaxter** [comment]
Actually, I don't even think I'm using that transformation... how come my predictions aren't between 0 and 1??

```
plot(trainX,colMeans(predict(model,trainX)),col="red",ty="l")
```

**Comment by XingLLiu** [comment]
Ah sorry I gave the wrong functional form. The value of the integral should indeed be 0.7. I was fiddling around the step function and forgot to change it back!

**Comment by flaxter** [comment]
Wait, I think I figured out the issue. If y is only ever 0 and 1 then dbarts automatically infers that this is a classification problem, not regression. Currently rerunning with 0 and 1 replaced by 1-e6 and 1-1e-6

**Comment by flaxter** [comment]
Seems to work now, happy for someone else to see if they can break this example though.

![image](https://user-images.githubusercontent.com/59355/66867794-f28bf400-ef93-11e9-8110-1e4d84524ce0.png)

[test_step_func.R.txt](https://github.com/flaxter/BO-BART/files/3731339/test_step_func.R.txt)

**Comment by harrisonzhu508** [comment]
- 2D mixture example
- visualise tree split
