### ISSUE TITLE
Get older version of DBARTs

### ISSUE THREAD

**Issue by harrisonzhu508** [flaxter/BO-BART#41]
dbarts_0.9-8.tar.gz  2018-12-19 00:11 
https://cran.r-project.org/src/contrib/Archive/dbarts/

This solves the deprecation issue

**Comment by harrisonzhu508** [comment]
https://cran.r-project.org/src/contrib/Archive/dbarts/dbarts_0.9-7.tar.gz

downloading from this link resolves the issue

**Comment by XingLLiu** [comment]
Installing the old version of dbart:
``
packageurl <- "https://cran.r-project.org/src/contrib/Archive/dbarts/dbarts_0.9-8.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
``

**Comment by flaxter** [comment]
What's the issue with the new version exactly? Can we email the author about this? He's been very responsive in the past.

**Comment by harrisonzhu508** [comment]
We can just specify the version of the dbarts package maybe for now in the README, although I agree that this is not ideal for the long term. Is it worth it to reimplement it in Python3 + C maybe?

**Comment by flaxter** [comment]
Possibly, but dbarts is pretty good and reimplementing it is a pain
(another student tried last year!) Let's just ask the author, Vince Dorie,
for help?

**Comment by harrisonzhu508** [comment]
Ah yeah that makes sense... Sure let's do that! (I might get involved in  developing `dbarts` in the future as well if I can squeeze in time)

**Comment by flaxter** [comment]
OK, here he is: https://datascience.columbia.edu/vincent-dorie

Are you in a position to describe the issue we're having and email him (cc'ing me)? Feel free to send me a draft first if you want.

**Comment by harrisonzhu508** [comment]
@harrisonzhu508  @flaxter  I am happy to write it, will try and replicate the error this weekend and send it to him
