### ISSUE TITLE
Should we be using a GP-BO package instead of doing it ourselves?

### ISSUE THREAD

**Issue by flaxter** [flaxter/BO-BART#47]
E.g. https://botorch.org

**Comment by harrisonzhu508** [comment]
This is making headway - using reticulate to pass R data structures to Python, where we optimise hyperparameters using gpytorch. The Python code will return the optimised value.

The GP lengthscale tuning is already implemented in `src/optimise_gp.R`. 

TODO:

- Implement Matern kernel for GP-BQ
    - Matern nu = 1/2, 3/2, 5/2

**Comment by harrisonzhu508** [comment]
Something is going wrong after the optimise_gp function is run in Python, it takes up all the memory. Will implement a version where the hyper parameters are stored as csvs
