### ISSUE TITLE
Non-uniform priors

### ISSUE THREAD

**Issue by flaxter** [flaxter/BO-BART#49]
One of the reviewers from last year didn't think our results could generalized beyond the setting of a uniform prior distribution. We discussed that we could address this quite easily by using BART on f(x)p(x) with a uniform prior rather than on f(x) with p(x) as a prior. Can we try this? p(x) could be the normal distribution or something more interesting, like Beta(2,5). Or we could try something hard, like f(x) = 1 and p(x) is the banana distribution: https://discourse.mc-stan.org/t/sampling-from-this-banana-shaped-distribution/2274/2

**Comment by harrisonzhu508** [comment]
Gaussian sufficient
