### ISSUE TITLE
As number of training points increases, without sequential design

### ISSUE THREAD

**Issue by harrisonzhu508** [flaxter/BO-BART#50]
I think it would be nice to produce a similar convergence plot without the sequential design, as the number of training points increases.

@XingLLiu  @RuyaKang  @OoAugust

**Comment by flaxter** [comment]
I might be missing the context---if not sequential design, how will points be chosen? Randomly?

**Comment by harrisonzhu508** [comment]
Just randomly, so we increase the number of training points . Would this make sense?

**Comment by flaxter** [comment]
Yes, that makes sense. Good to compare BART and GPs in this setting.

**Comment by XingLLiu** [comment]
Sounds good. I can try coding it up over the weekend.

**Comment by harrisonzhu508** [comment]
@XingLLiu  any update?

**Comment by XingLLiu** [comment]
Coded this up. Just got time to try 3-dim copeak for 100 iterations.

For details of code please see the pull request.

[copeak3DimNoSequential.pdf](https://github.com/flaxter/BO-BART/files/3908794/copeak3DimNoSequential.pdf)

**Comment by harrisonzhu508** [comment]
Cheers. I added some comments in the PR. There's also a merge conflict which you just need to do `git rm --cached ` to fix. More details in the PR comments.

**Comment by harrisonzhu508** [comment]
@flaxter  @XingLLiu  @OoAugust  @RuyaKang 

Here are some results without sequential design for the continuous genz. BART-BQ is dominating in higher dimensions!

[cont1DimNoSequential.pdf](https://github.com/flaxter/BO-BART/files/3934974/cont1DimNoSequential.pdf)
[cont2DimNoSequential.pdf](https://github.com/flaxter/BO-BART/files/3934975/cont2DimNoSequential.pdf)
[cont3DimNoSequential.pdf](https://github.com/flaxter/BO-BART/files/3934976/cont3DimNoSequential.pdf)
[cont5DimNoSequential.pdf](https://github.com/flaxter/BO-BART/files/3934977/cont5DimNoSequential.pdf)
[cont10DimNoSequential.pdf](https://github.com/flaxter/BO-BART/files/3934979/cont10DimNoSequential.pdf)
[cont20DimNoSequential.pdf](https://github.com/flaxter/BO-BART/files/3934980/cont20DimNoSequential.pdf)
