### ISSUE TITLE
Function 7 - Step Function

### ISSUE THREAD

**Issue by harrisonzhu508** [flaxter/BO-BART#53]
The jump option is not incorporated into the sequential design. Currently the step function only works for jump=1, which is the default. Refactoring needed

**Comment by XingLLiu** [comment]
See pull request #58 

Step function:
For k = number of jumps + 1,
f(x) =
- 0,   if x_1 < 1/k;
- j/k,  if j/k < x_1 <= (j + 1)/k, for j = 1, ..., k-1,
where x \in \R^d


Integral over [0, 1] = 0.5 * (2 + k) * (k - 1) / k^2

**Comment by harrisonzhu508** [comment]
sbart - interesting extension. It works for smooth things - deserves a citation for genericity
