### ISSUE TITLE
Computational Complexity with BART Quadrature

### ISSUE THREAD

**Issue by harrisonzhu508** [flaxter/BO-BART#6]
The computational complexity seems to be very high, especially as we are building a regression tree each time we implement query sequential design.

Any thoughts?

**Comment by harrisonzhu508** [comment]
August added in C++ code in `GPBQ.R` to optimise matrix inversion, but the main issue is with the use of `pmvnorm`. Not much we can do about this.

**Comment by OoAugust** [comment]
BART can be written into Rcpp if we have enough time, but not the priority now.
